name: Setup
description: ""

runs:
  using: composite
  steps:
    - uses: aquaproj/aqua-installer@f13c5d2f0357708d85477aabe50fd3f725528745 # v3.1.0
      with:
        aqua_version: v2.42.2
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
