version: 2

before:
  hooks:
    - go mod tidy
    - ./scripts/build-completions.sh
builds:
  - ldflags:
      - -s -w -X github.com/koki-develop/gat/cmd.version=v{{.Version}}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin

archives:
  - formats: [tar.gz]
    files:
      - completions/*
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
    - goos: windows
      formats: [zip]
checksum:
  name_template: 'checksums.txt'
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

brews:
  - repository:
      owner: koki-develop
      name: homebrew-tap
      token: "{{ .Env.TAP_GITHUB_TOKEN }}"
    directory: Formula
    install: |
      bin.install "gat"
      bash_completion.install "completions/gat.bash" => "gat"
      zsh_completion.install "completions/gat.zsh" => "_gat"
      fish_completion.install "completions/gat.fish"
