name: Review Renovate

permissions: {}

on:
  pull_request:
    types:
      - opened
      - edited

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  review:
    if: github.event.pull_request.user.login == 'renovate[bot]'
    timeout-minutes: 30
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false
      - uses: ./.github/actions/claude-renovate-review
        id: review
        with:
          github_token: ${{ github.token }}
          pull_request_number: ${{ github.event.pull_request.number }}
          claude_code_oauth_token: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}
      - name: debug
        env:
          REVIEW_REPORT: ${{ steps.review.outputs.report }}
        run: echo "$REVIEW_REPORT"
